### ISSUE TITLE
Path parsing issue

### ISSUE THREAD

**Issue by Peder2911** [prio-data/views_job_manager#2]
Found a disconcerting traceback in the server logs while the system was in use:
```
job-manager_1          | Traceback (most recent call last):
...
job-manager_1          |   File "/job_manager/app.py", line 33, in dispatch
job-manager_1          |     job = Job.parse_whole_path(path)
job-manager_1          |   File "/job_manager/models.py", line 48, in parse_whole_path
job-manager_1          |     level_of_analysis,*tail = PurePath(path).parts
job-manager_1          | ValueError: not enough values to unpack (expected at least 1, got 0)
```
I was not expecting any issues related to paths, so this was surprising.

**Comment by Peder2911** [comment]
This is the queryset that was requested:
```
my_queryset = Queryset(
        name = "my_queryset",
        loa = "priogrid_month",
        themes = ["testing"],
        operations = [
                [
                    DatabaseOperation(name="country.name",arguments=["values"])
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.acled_count_pr",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_ns",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_os",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["2"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["3"]),
                    TransformOperation(name="lags.splag",arguments=["1","1","0","0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["2"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["3"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["4"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["5"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["6"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["7"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["8"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["9"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["10"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["11"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["12"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_ns",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_os",arguments=["values"]),
                ],
                [
                    TransformOperation(name="lags.tlag",arguments=["1"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.acled_count_pr",arguments=["values"]),
                ],
                [
                    TransformOperation(name="temporal.decay",arguments=["12"]),
                    TransformOperation(name="temporal.time_since",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.acled_count_pr",arguments=["values"]),
                ],
                [
                    TransformOperation(name="temporal.decay",arguments=["12"]),
                    TransformOperation(name="temporal.time_since",arguments=["0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_ns",arguments=["values"]),
                ],
                [
                    TransformOperation(name="temporal.decay",arguments=["12"]),
                    TransformOperation(name="temporal.time_since",arguments=["0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_os",arguments=["values"]),
                ],
                [
                    TransformOperation(name="temporal.decay",arguments=["12"]),
                    TransformOperation(name="temporal.time_since",arguments=["0"]),
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
                [
                    TransformOperation(name="ops.gte",arguments=["0"]),
                    DatabaseOperation(name="priogrid_month.ged_best_sb",arguments=["values"]),
                ],
            ]
    )
```
